apiVersion: apps/v1
kind: Deployment
metadata:
  name: javawebapp-deployment
spec:
  revisionHistoryLimit: 10
  replicas: 2
  selector:
    matchLabels:
      app: javawebapp
  template:
    metadata:
      name: javawebapp-pod
      labels:
        app: javawebapp
    spec:
      containers:
        - name: javawebapp-container
          image: 124314579054.dkr.ecr.ap-south-1.amazonaws.com/test-ns/eks-demo:BUILD_NUMBER   # Jenkins can update tag with build number
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: javawebapp-service
spec:
  selector:
    app: javawebapp
  type: LoadBalancer   # You can switch to LoadBalancer if using cloud provider
  ports:
    - port: 80
      targetPort: 8080  
