apiVersion: apps/v1
kind: Deployment
metadata:
  name: javawebapp-deployment
spec:
  revisionHistoryLimit: 10
  replicas: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: javawebapp
  template:
    metadata:
      name: javawebapp-pod
      labels:
        app: javawebapp
    spec:
      containers:
        - name: javawebapp-container
          image: vikrampolollu/java-web-app-docker:latest   # Jenkins can update tag with build number
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: javawebapp-service
spec:
  selector:
    app: javawebapp
  type: LoadBalancer   # You can switch to LoadBalancer if using cloud provider
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080   # Optional: explicitly set NodePort (range 30000–32767)
